// realmap.js -- cartographic "Real map" layer (OpenStreetMap footprints, roads, green space) drawn in the SAME
// world frame as the tile map: data in tiles (1 tile = 32 px), camera math screen = (worldPx - cam) * zoom.
// Data: /static/homewood_vector.json, generated by scripts/export_realmap.py (do not hand-edit).
//
// INTEGRATION (app.js, lead to apply):
//   1. top of app.js:      import { loadRealMap, drawRealMap, REALMAP_ATTRIBUTION } from "./realmap.js";
//   2. in init, after the tile map loads:  loadRealMap().catch(() => {});   (S.mapMode = "tiles" | "real")
//   3. in draw(), replace the line `drawChunks(ctx, false);` with
//        if (S.mapMode === "real") drawRealMap(ctx, cam, { dpr }); else drawChunks(ctx, false);
//      drawRealMap sets the same world transform app.js uses (z = cam.zoom*dpr, translate -cam*z) and leaves it set,
//      so the active-place outlines and agents drawn afterwards line up unchanged.
//   4. after the agent/overlay layer (screen space), for labels on top of agents (optional):
//        if (S.mapMode === "real") drawRealMapLabels(ctx, cam, { dpr });
//      and show REALMAP_ATTRIBUTION in a corner (e.g. a small <div class="attrib"> over #map) whenever mode is real.
//   5. a Tiles/Real toggle button that flips S.mapMode and calls draw().
// Also works as a classic script: window.RealMap = { loadRealMap, drawRealMap, drawRealMapLabels, ... }.

export const REALMAP_ATTRIBUTION = "© OpenStreetMap contributors";
const TILE = 32;
const C = {
  ground: "#f2efe9", green: "#cfe6b8", greenEdge: "#b3d39a", water: "#aad3df", parking: "#e4e0d8",
  building: "#d9d0c9", buildingEdge: "#bcb0a6", place: "#f3c98b", placeEdge: "#c77d2e",
  road: "#ffffff", roadCase: "#c8c2b8", path: "#e8927c", label: "#3b3632", placeLabel: "#6b3a0c", halo: "rgba(255,255,255,0.9)",
};
let V = null, loading = null;

export function loadRealMap(url = "/static/homewood_vector.json") {
  if (V) return Promise.resolve(V);
  if (!loading) loading = fetch(url).then((r) => r.json()).then((d) => (V = prepare(d)));
  return loading;
}
export function realMapReady() { return !!V; }

function bbox(p) {
  let a = Infinity, b = Infinity, c = -Infinity, d = -Infinity;
  for (const [x, y] of p) { if (x < a) a = x; if (y < b) b = y; if (x > c) c = x; if (y > d) d = y; }
  return [a, b, c, d];
}
function toPath(p, close) {
  const g = new Path2D(); g.moveTo(p[0][0] * TILE, p[0][1] * TILE);
  for (let i = 1; i < p.length; i++) g.lineTo(p[i][0] * TILE, p[i][1] * TILE);
  if (close) g.closePath();
  return g;
}
function merge(list, close) { const g = new Path2D(); for (const p of list) g.addPath(toPath(p, close)); return g; }

function prepare(d) {
  const bld = d.buildings.map((b) => ({ ...b, bb: bbox(b.p) }));
  const placeBoxes = d.places.flatMap((pl) => pl.boxes.map((bx) => ({ pl, bx })));
  // flag footprints whose centre falls inside a simulation place box
  const flagged = [], plain = [];
  for (const b of bld) {
    const cx = (b.bb[0] + b.bb[2]) / 2, cy = (b.bb[1] + b.bb[3]) / 2;
    const hit = placeBoxes.find(({ bx }) => cx >= bx[0] && cx <= bx[2] + 1 && cy >= bx[1] && cy <= bx[3] + 1);
    if (hit) { b.place = hit.pl.id; flagged.push(b.p); } else plain.push(b.p);
  }
  const wide = new Set(["primary", "secondary", "trunk", "primary_link", "secondary_link"]);
  return {
    raw: d, buildings: bld,
    g: {
      green: merge(d.greens, true), water: merge(d.water, true), parking: merge(d.parking, true),
      pathArea: merge(d.paths.filter((p) => p.area).map((p) => p.p), true),
      paths: merge(d.paths.filter((p) => !p.area).map((p) => p.p), false),
      roadsWide: merge(d.roads.filter((r) => wide.has(r.k)).map((r) => r.p), false),
      roads: merge(d.roads.filter((r) => !wide.has(r.k)).map((r) => r.p), false),
      waterways: merge(d.waterways, false),
      bld: merge(plain, true), place: merge(flagged, true),
    },
  };
}

function worldTransform(ctx, cam, dpr) {
  const z = cam.zoom * dpr;
  ctx.setTransform(z, 0, 0, z, -cam.x * z, -cam.y * z);
  return z;
}

// Draws the base map in world space. opts: { dpr=1, labels=true, highlight: Set of place ids }
export function drawRealMap(ctx, cam, opts = {}) {
  const dpr = opts.dpr || 1;
  if (!V) return false;
  const G = V.g, zm = cam.zoom, px = (n) => n / zm;   // px(n): n screen px in world units
  ctx.save();
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.fillStyle = C.ground; ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
  worldTransform(ctx, cam, dpr);
  ctx.lineJoin = "round"; ctx.lineCap = "round";
  ctx.fillStyle = C.green; ctx.fill(G.green);
  ctx.fillStyle = C.parking; ctx.fill(G.parking);
  ctx.fillStyle = C.water; ctx.fill(G.water);
  ctx.strokeStyle = C.water; ctx.lineWidth = Math.max(px(2), 0.6 * TILE); ctx.stroke(G.waterways);
  ctx.fillStyle = "#f4e9dc"; ctx.fill(G.pathArea);
  // roads: casing then fill; real widths (m) floored to a visible screen width
  const rw = Math.max(px(3), 3.5 * TILE), ww = Math.max(px(4.5), 6 * TILE);
  ctx.strokeStyle = C.roadCase; ctx.lineWidth = rw + px(1.5); ctx.stroke(G.roads); ctx.lineWidth = ww + px(1.5); ctx.stroke(G.roadsWide);
  ctx.strokeStyle = C.road; ctx.lineWidth = rw; ctx.stroke(G.roads);
  ctx.strokeStyle = "#fcd6a4"; ctx.lineWidth = ww; ctx.stroke(G.roadsWide);
  ctx.strokeStyle = C.path; ctx.lineWidth = Math.min(px(2), Math.max(px(1), 0.25 * TILE)); ctx.lineCap = "butt";
  if (zm >= 0.12) { ctx.setLineDash([px(4), px(3)]); ctx.stroke(G.paths); ctx.setLineDash([]); } else { ctx.globalAlpha = 0.5; ctx.stroke(G.paths); ctx.globalAlpha = 1; }
  ctx.lineCap = "round";
  ctx.fillStyle = C.building; ctx.fill(G.bld);
  ctx.strokeStyle = C.buildingEdge; ctx.lineWidth = px(1); ctx.stroke(G.bld);
  ctx.fillStyle = C.place; ctx.fill(G.place);
  ctx.strokeStyle = C.placeEdge; ctx.lineWidth = px(1.5); ctx.stroke(G.place);
  // outdoor simulation places (quads, fields...) as dashed outlines of their boxes
  ctx.strokeStyle = C.placeEdge; ctx.lineWidth = px(1.5); ctx.setLineDash([px(5), px(4)]);
  for (const pl of V.raw.places) if (pl.kind !== "building")
    for (const [x0, y0, x1, y1] of pl.boxes) ctx.strokeRect(x0 * TILE, y0 * TILE, (x1 - x0 + 1) * TILE, (y1 - y0 + 1) * TILE);
  ctx.setLineDash([]);
  ctx.restore();
  worldTransform(ctx, cam, dpr);   // leave the world transform set for the caller (as app.js expects)
  if (opts.labels) drawRealMapLabels(ctx, cam, opts);
  return true;
}

// Screen-space labels: simulation places always, other named buildings and streets when zoomed in.
export function drawRealMapLabels(ctx, cam, opts = {}) {
  if (!V) return;
  const dpr = opts.dpr || 1, zm = cam.zoom;
  const sx = (wx) => (wx * TILE - cam.x) * zm * dpr, sy = (wy) => (wy * TILE - cam.y) * zm * dpr;
  ctx.save(); ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.lineJoin = "round";
  const text = (s, x, y, font, color) => {
    ctx.font = font; ctx.lineWidth = 3 * dpr; ctx.strokeStyle = C.halo; ctx.strokeText(s, x, y); ctx.fillStyle = color; ctx.fillText(s, x, y);
  };
  if (zm >= 0.3) {
    for (const r of V.raw.roads) if (r.n) { const m = r.p[Math.floor(r.p.length / 2)]; text(r.n, sx(m[0]), sy(m[1]), `italic ${10 * dpr}px system-ui, sans-serif`, "#6f6a64"); }
    for (const b of V.buildings) if (b.n && !b.place) text(b.n, sx((b.bb[0] + b.bb[2]) / 2), sy((b.bb[1] + b.bb[3]) / 2), `${10 * dpr}px system-ui, sans-serif`, C.label);
  }
  const f = Math.round((zm >= 0.3 ? 12 : 10.5) * dpr);
  for (const pl of V.raw.places) {
    const [x0, y0, x1, y1] = pl.boxes[0];
    text(zm >= 0.2 ? pl.label : pl.id, sx((x0 + x1 + 1) / 2), sy((y0 + y1 + 1) / 2), `600 ${f}px system-ui, sans-serif`, C.placeLabel);
  }
  if (opts.attribution) {
    ctx.font = `${10 * dpr}px system-ui, sans-serif`; ctx.textAlign = "right"; ctx.textBaseline = "bottom";
    const w = ctx.measureText(REALMAP_ATTRIBUTION).width, X = ctx.canvas.width - 4 * dpr, Y = ctx.canvas.height - 3 * dpr;
    ctx.fillStyle = "rgba(255,255,255,0.8)"; ctx.fillRect(X - w - 6 * dpr, Y - 13 * dpr, w + 10 * dpr, 15 * dpr);
    ctx.fillStyle = "#333"; ctx.fillText(REALMAP_ATTRIBUTION, X, Y);
  }
  ctx.restore();
}

if (typeof window !== "undefined") window.RealMap = { loadRealMap, drawRealMap, drawRealMapLabels, realMapReady, REALMAP_ATTRIBUTION };
