p0001:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0006:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0009:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0015:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0022:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0023:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0027:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0028:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0031:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0033:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0042:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0047:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0051:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0054:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0057:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0058:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0067:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0085:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0086:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0088:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0098:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0105:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0108:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0112:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0121:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0124:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0135:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0139:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0146:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0150:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0159:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0165:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0168:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0170:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0177:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0181:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0184:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0187:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0190:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0197:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0206:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0208:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0209:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0211:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0213:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0227:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0230:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0237:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0238:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0239:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0243:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0248:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0260:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0263:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0270:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0274:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0277:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0286:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0291:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0293:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0306:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0309:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0310:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0318:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0319:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0323:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0325:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0329:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0339:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0351:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0359:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0361:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0362:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0366:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0367:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0371:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0375:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0380:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0385:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0407:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0414:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0416:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0420:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0421:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0437:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0444:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0453:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0454:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0457:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0458:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0459:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0460:
- In my recent everyday conversations, I have called the dining hall beside AMR III Hopkins Cafe when arranging
  meals. I have eaten or worked at that physical dining hall.
p0464:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0468:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0469:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0477:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0478:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0480:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0485:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
p0486:
- In my recent everyday conversations, I have called the dining hall beside AMR III FFC when arranging meals. I
  have eaten or worked at that physical dining hall.
