"""Render docs/TRACE_SCHEMA.md from the trace registry (backend/tracing/schema.py).

    .venv/bin/python scripts/trace_schema_doc.py            # (re)write docs/TRACE_SCHEMA.md
    .venv/bin/python scripts/trace_schema_doc.py --check    # exit 1 if the file is out of date
    .venv/bin/python scripts/trace_schema_doc.py --stdout   # print instead of writing
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.tracing.schema import ENVELOPE, FRAME_SCHEMA, LAYERS, TRACE_TYPES  # noqa: E402

OUT = ROOT / "docs" / "TRACE_SCHEMA.md"

LAYER_TEXT = {
    "world": "the WORLD layer (world script, movement, co-op machine, binder, roster): what happened",
    "agent": "the AGENT layer (perception, memory, talk, decisions): what agents noticed, kept, said and chose",
    "controller": "the EXPERIMENT CONTROLLER (checkpoints, branches)",
    "observer": "the OBSERVER (backend/analysis): never writes the simulation trace; no types",
}

API = """\
All endpoints take `?debug=1` (Research Debug Mode) to skip demo-mode stripping. Run ids are paths under the
runs root (`<run>` or `<design>/<cell>/s<seed>`).

| endpoint | returns |
|---|---|
| `GET /api/schema` | `{envelope, layers, types: {type: {layer, since, section, description, required, optional}}, frame}`; debug adds hidden types and `hidden`, `hidden_fields`, `required_if` |
| `GET /api/runs/<id>/frames` | the frames (below), stripped in demo mode |
| `GET /api/runs/<id>/trace` | records, oldest first. Filters: `type` (comma list; `types` still works), `agent` (any record involving the agent), `tick_from` / `tick_to` (inclusive; `start` / `end` still work), `conversation` (a conversation record and every record with its `conversation_id`), `limit` (default 5000, counted after filtering). Hidden types are dropped and hidden fields removed in demo mode |
| `GET /api/runs/<id>/coop` | the co-op view of a v3 run (below); v2 runs get the same shape with empty lists and `enabled: false` |

`GET /api/runs/<id>/coop`:
```
{run_id, enabled, mechanisms: {workshop, records, roster, turnover},
 jobs: [{job, day, slot, shift, operator, project, start_tick, symptom,
         decisions: [{tick, time, attempt, choice, action, question, ask_target, says_aloud, reason, valid, consult,
                      binder_shown, binder_chosen, binder_entry_ids}],
         clarifications: [{tick, time, attempt, agent, target, question, conversation_id}],
         attempts: [{tick, time, attempt, action, outcome, text}],
         end: {tick, time, delivered, result} | null,
         writes: [binder entry / revision ids the operator wrote after the job],
         truth (debug only): {regime, mapping, class, cause, fault, gt, u_attempt, code, p, ...}}],
 binder: {timeline: [{kind: "write", tick, time, agent, author_name, offer, choice, entry_id, rev_id, text,
                      truncated, job}
                   | {kind: "transition", tick, time, day, mode, archived_binder_id, binder_id}
                   | {kind: "read", tick, time, agent, context, view_mode, new_ids, shown_ids}],
          state: {binder_id, front: [{rev_id, author, author_name, tick, time, text, offer}],
                  log: [{entry_id, author, author_name, tick, time, text, offer}],
                  archived: [{binder_id, archived_tick, front, log}]}},
 roster_changes: [{tick, time, day, agent, kind: depart|arrive, role, replaces?}],
 onboarding: [{tick, time, agent, day, ties: [{with, relation_type, familiarity, affinity}]}],
 farewells: [{tick, time, agent, day, role, location, arena, text}],
 tallies: [{tick, time, day, delivered, total, missing, text, stores}],
 cues: [{tick, time, cue, day, arena, text_key, text}],
 handovers: [{tick, time, day, outgoing, incoming, conversation_id}],
 meetings: [{tick, time, day, invited, conversation_id}],
 days: [{tick, time, day, counts}], checkpoints: [{id, tick, time}],
 regimes (debug only): [{tick, time, day, regime, mapping, changed}]}
```
"""


def _fields(xs) -> str:
    return ", ".join(f"`{x}`" for x in xs) if xs else "none"


def _cell(text: str) -> str:
    """A markdown table cell: pipes inside the text must not end the cell."""
    return str(text).replace("|", "\\|")


def render() -> str:
    L = ["# MemeWorld trace schema", "",
         "Generated by `scripts/trace_schema_doc.py` from `backend/tracing/schema.py`; do not edit by hand. "
         "`tests/test_trace_schema.py` checks that this file is current and that every record type a mock v2 "
         "all-on day and a mock v3 co-op day emit is registered with its required fields.", "",
         "## Envelope", "",
         f"Every line of `trace.jsonl` is one JSON record with {_fields(ENVELOPE)} (written by "
         "`TraceLogger.log`). `id` is `<scope>#<n>` unless the record sets its own (utterances, conversations, "
         "checkpoints); a record may also set its own `tick` (e.g. `job_start`). Run with "
         "`MEMEWORLD_TRACE_CHECK=1` to have the logger warn (never fail) on unregistered types or missing "
         "required fields.", "",
         "## Layers", ""]
    L += [f"- **{k}**: {LAYER_TEXT[k]}" for k in LAYERS]
    L += ["", "## Demo mode", "",
          "The API without `?debug=1` applies the registry to every trace record it serves: a **hidden** type is "
          "dropped, a public type loses its **hidden fields** (dotted paths reach into nested objects). The "
          "server's generic filters (`HIDDEN_KEYS`, `HIDDEN_VALUE`, `HIDDEN_PATHS` in `backend/api/server.py`) "
          "run afterwards as a second line of defence.", "",
          "## Index", "", "| type | layer | since | demo mode | defined in | description |", "|---|---|---|---|---|---|"]
    for layer in LAYERS:
        for t, s in sorted(TRACE_TYPES.items()):
            if s["layer"] != layer:
                continue
            demo = "hidden" if s["hidden"] else ("strips " + _fields(s["hidden_fields"]) if s["hidden_fields"]
                                                 else "public")
            L.append(f"| `{t}` | {layer} | {s['since']} | {demo} | {_cell(s['section'])} | "
                     f"{_cell(s['description'])} |")
    for layer in LAYERS:
        types = sorted(t for t, s in TRACE_TYPES.items() if s["layer"] == layer)
        if not types:
            continue
        L += ["", f"## {layer.capitalize()} records", ""]
        for t in types:
            s = TRACE_TYPES[t]
            L += [f"### `{t}`", "", s["description"], "",
                  f"- defined in: {s['section']} (since {s['since']})",
                  f"- required: {_fields(s['required'])}"]
            if s["required_if"]:
                L.append("- required when: " + ", ".join(f"`{f}` if `{o}` == `{v}`"
                                                          for f, (o, v) in s["required_if"].items()))
            if s["optional"]:
                L.append(f"- optional: {_fields(s['optional'])}")
            if s["hidden"]:
                L.append("- demo mode: **whole record hidden**")
            elif s["hidden_fields"]:
                L.append(f"- demo mode strips: {_fields(s['hidden_fields'])}")
            L.append("")
        if L[-1] == "":
            L.pop()
    L += ["", "## Frames (`frames.jsonl`)", "",
          "One line per tick, written by `engine._frame` after the tick's trace. Fields added after v2 may be "
          "missing in older runs; readers must default them.", ""]
    for part, fields in FRAME_SCHEMA.items():
        L += [f"### `{part}`", "", "| field | meaning |", "|---|---|"]
        L += [f"| `{k}` | {_cell(v)} |" for k, v in fields.items()]
        L.append("")
    L += ["## API", "", API]
    return "\n".join(L).rstrip() + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/TRACE_SCHEMA.md is out of date")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    ap.add_argument("--out", default=str(OUT))
    a = ap.parse_args(argv)
    text = render()
    if a.stdout:
        sys.stdout.write(text)
        return 0
    out = Path(a.out)
    if a.check:
        ok = out.exists() and out.read_text() == text
        if not ok:
            print(f"{out} is out of date: run scripts/trace_schema_doc.py", file=sys.stderr)
        return 0 if ok else 1
    out.write_text(text)
    print(f"wrote {out} ({len(TRACE_TYPES)} record types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
