"""Hidden latent event families and the EventInstance record (ontology v2 §1.7).

SIMULATOR-ONLY. Family ids, schemas, skins, circles and the assignment never reach an agent:
agents only receive individual *facts* (concrete surface sentences) through partial perception
(backend/agents/perception.py). The API strips the hidden keys in demo mode.

v2 instances are pre-generated by world_script.generate() from structure schemas x surface skins
(structures.py, skins/). The v1 scenario scripts live in legacy_scenarios_v1.py and are re-exported
below so the pre-v2 engine path keeps working until it is switched over.
"""
from __future__ import annotations

from dataclasses import dataclass, field

LATENT_TYPES = {
    "E0": {"name": "plain_mishaps", "description": "unconnected everyday mishaps, no shared structure (control)"},
    "E1": {"name": "cascade_failure", "description": "a small initial mistake creates a chain of otherwise unrelated failures"},
    "E2": {"name": "cancelling_mistakes", "description": "two independent mistakes accidentally cancel out and nothing goes wrong"},
    "E3": {"name": "independent_coincidence", "description": "unrelated people independently do the same unusual thing"},
    "E4": {"name": "beneficial_failure", "description": "an apparent failure causes a beneficial outcome"},
}

# fields of the §1.7 record, in output order
RECORD_KEYS = ("id", "latent_type", "structure_mode", "schema", "skin", "composed_from", "holdout", "start_tick",
               "generator", "roles", "circle", "cast_from_home", "referents", "beats", "narrative")
# keys the API must strip in demo mode ("scenario" is the v1 alias of "skin")
HIDDEN_KEYS = ("latent_type", "schema", "skin", "composed_from", "structure_mode", "circle", "cast_from_home",
               "narrative", "scenario")


@dataclass
class EventInstance:
    id: str
    latent_type: str
    scenario: str | None           # v1 scenario key; v2: the skin key (None when composed)
    holdout: bool
    start_tick: int
    roles: dict                    # role -> {"agent": id|None, "name": display name}
    beats: list                    # concrete beats (absolute tick, location, arena, facts, movers)
    generator: str = "template"
    fired: set = field(default_factory=set)
    # v2 (§1.7); defaults keep v1 construction working
    structure_mode: str = "real"
    schema: str | None = None
    skin: str | None = None
    composed_from: list | None = None
    circle: str | None = None
    cast_from_home: bool = False
    referents: list = field(default_factory=list)
    narrative: str | None = None

    def ground_truth(self) -> dict:
        narrative = self.narrative
        if narrative is None:
            narrative = " ".join(f["text"] for b in self.beats for f in b["facts"])
        rec = {"id": self.id, "latent_type": self.latent_type, "structure_mode": self.structure_mode,
               "schema": self.schema, "skin": self.skin, "composed_from": self.composed_from,
               "holdout": self.holdout, "start_tick": self.start_tick, "generator": self.generator,
               "roles": self.roles, "circle": self.circle, "cast_from_home": self.cast_from_home,
               "referents": self.referents, "beats": self.beats, "narrative": narrative}
        rec["scenario"] = self.scenario   # v1 readers (API, diagnose script) still look this up
        return rec

    @classmethod
    def from_dict(cls, d: dict) -> "EventInstance":
        """Inverse of ground_truth() (world_script.jsonl / events.jsonl line -> instance)."""
        return cls(id=d["id"], latent_type=d["latent_type"], scenario=d.get("scenario", d.get("skin")),
                   holdout=bool(d.get("holdout", False)), start_tick=int(d["start_tick"]), roles=d["roles"],
                   beats=d["beats"], generator=d.get("generator", "template"),
                   structure_mode=d.get("structure_mode", "real"), schema=d.get("schema"), skin=d.get("skin"),
                   composed_from=d.get("composed_from"), circle=d.get("circle"),
                   cast_from_home=bool(d.get("cast_from_home", False)), referents=d.get("referents") or [],
                   narrative=d.get("narrative"))


# v1 compatibility (pre-v2 engine path, probes, legacy tests). Imported after EventInstance and
# LATENT_TYPES exist; the legacy module imports them lazily, so there is no import cycle.
from backend.simulation.legacy_scenarios_v1 import (  # noqa: E402,F401
    B, F, LLM_GEN_PROMPT, NPC_Q, NPC_S, SCENARIOS, _fill, assign_home_groups, instantiate, llm_scenario,
    scenarios_for)
